/**
 * Created by Zipeng Liu on 2016-11-29.
 */

export const FETCH_DATASETS_REQUEST = 'FETCH_DATASETS_REQUEST';
export const FETCH_DATASETS_SUCCESS = 'FETCH_DATASETS_SUCCESS';
export const FETCH_DATASETS_FAILURE = 'FETCH_DATASETS_FAILURE';

export const FETCH_INPUT_GROUP_REQUEST = 'FETCH_INPUT_GROUP_REQUEST';
export const FETCH_INPUT_GROUP_SUCCESS = 'FETCH_INPUT_GROUP_SUCCESS';
export const FETCH_INPUT_GROUP_FAILURE = 'FETCH_INPUT_GROUP_FAILURE';

// OVERALL
export const TOGGLE_SELECT_TREES = 'TOGGLE_SELECT_TREES';

// Reference Tree actions
export const TOGGLE_HIGHLIGHT_MONOPHYLY = 'TOGGLE_HIGHLIGHT_MONOPHYLY';
export const SELECT_BRANCH = 'SELECT_BRANCH';
export const FETCH_TREE_REQUEST = 'FETCH_TREE_REQUEST';
export const FETCH_TREE_SUCCESS = 'FETCH_TREE_SUCCESS';
export const FETCH_TREE_FAILURE = 'FETCH_TREE_FAILURE';
export const CLEAR_ALL_SELECTION_AND_HIGHLIGHT = 'CLEAR_ALL_SELECTION_AND_HIGHLIGHT';
export const TOGGLE_CHECKING_BRANCH = 'TOGGLE_CHECKING_BRANCH';
export const TOGGLE_UNIVERSAL_BRANCH_LENGTH = 'TOGGLE_UNIVERSAL_BRANCH_LENGTH';
export const TOGGLE_HIGHLIGHT_DUPLICATE = 'TOGGLE_HIGHLIGHT_DUPLICATE';
export const TOGGLE_REFERENCE_TREE_ATTRIBUTE_EXPLORER = 'TOGGLE_REFERENCE_TREE_ATTRIBUTE_EXPLORER';
export const TOGGLE_POP_ATTRIBUTE_EXPLORER = 'TOGGLE_POP_ATTRIBUTE_EXPLORER';

// Overview actions
export const POP_CREATE_NEW_SET_WINDOW = 'POP_CREATE_NEW_SET_WINDOW';
export const CLOSE_CREATE_NEW_SET_WINDOW = 'CLOSE_CREATE_NEW_SET_WINDOW';
export const CREATE_NEW_SET = 'CREATE_NEW_SET';
export const TYPING_TITLE = 'TYPING_TITLE';
export const REMOVE_SET = 'REMOVE_SET';
export const ADD_TO_SET = 'ADD_TO_SET';
export const START_SELECTION = 'START_SELECTION';
export const END_SELECTION = 'END_SELECTION';
export const CHANGE_SELECTION = 'CHANGE_SELECTION';
export const CHANGE_DISTANCE_METRIC_REQUEST = 'CHANGE_DISTNACE_METRIC_REQUEST';
export const CHANGE_DISTANCE_METRIC_SUCCESS = 'CHANGE_DISTNACE_METRIC_SUCCESS';
export const CHANGE_DISTANCE_METRIC_FAILURE = 'CHANGE_DISTNACE_METRIC_FAILURE';

// Aggregated dendrogram actions
export const SELECT_SET = 'SELECT_SET';
export const REMOVE_FROM_SET = 'REMOVE_FROM_SET';
export const CHANGE_SORTING = 'CHANGE_SORTING';
export const TOGGLE_AGGREGATION_MODE = 'TOGGLE_AGGREGATION_MODE';
export const TOGGLE_HIGHLIGHT_ENTITIES = 'TOGGLE_HIGHLIGHT_ENTITIES';

// Inspector
export const TOGGLE_INSPECTOR = 'TOGGLE_INSPECTOR';
export const ADD_TREE_TO_INSPECTOR = 'ADD_TO_INSPECTOR';
export const REMOVE_TREE_FROM_INSPECTOR = 'REMOVE_TREE_FROM_INSPECTOR';
export const TOGGLE_PAIRWISE_COMPARISON = 'TOGGLE_PAIRWISE_COMPARISON';
export const COMPARE_WITH_REFERENCE = 'COMPARE_WITH_REFERENCE';

// Attribute Explorer
export const CHANGE_ATTRIBUTE_EXPLORER_MODE = 'CHANGE_ATTRIBUTE_EXPLORER_MODE';
export const MOVE_CONTROL_HANDLE = 'MOVE_CONTROL_HANDLE';
export const TOGGLE_MOVE_HANDLE = 'TOGGLE_MOVE_HANDLE';
export const CHANGE_SELECTION_RANGE = 'CHANGE_SELECTION_RANGE';
export const TOGGLE_HISTOGRAM_OR_CDF = 'TOGGLE_HISTOGRAM_OR_CDF';
export const CHANGE_ACTIVE_RANGE_SELECTION = 'CHANGE_ACTIVE_RANGE_SELECTION';
export const CHANGE_ACTIVE_EXPANDED_BRANCH = 'CHANGE_ACTIVE_EXPANDED_BRANCH';

// Tree list
export const TOGGLE_TREE_LIST_COLLAPSE = 'TOGGLE_TREE_LIST_COLLAPSE';


// Global
export const TOGGLE_JACCARD_MISSING = 'TOGGLE_JACCARD_MISSING';
export const CLOSE_TOAST = 'CLOSE_TOAST';


// Taxa List
export const TOGGLE_TAXA_LIST = 'TOGGLE_TAXA_LIST';
export const TOGGLE_SELECT_TAXA = 'TOGGLE_SELECT_TAXA';


// Tree Distribution
export const TOGGLE_SHOW_SUBSET_DISTRIBUTION = 'TOGGLE_SHOW_SUBSET_DISTRIBUTION';
export const TOGGLE_HIGHLIGHT_TREES = 'TOGGLE_HIGHLIGHT_TREES';


// Global Toolkit
export const CLEAR_SELECTED_TREES = 'CLEAR_SELECTED_TREES';
